spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_auth
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

server:
  port: 8081

# JWT Configuration
jwt:
  secret: mySecretKeyForJWTTokenGenerationWhichShouldBeLongEnoughAndSecure
  access-token-expiration: 3600000  # 1 hour in milliseconds
  refresh-token-expiration: 7       # 7 days

user-service:
  url: http://localhost:8082

# Feign Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    com.ecommerce.authservice: DEBUG
    org.hibernate.SQL: DEBUG